import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildTokensCss } from '../src/tokens.ts'

/**
 * Writes the generated token stylesheet to `dist/tokens.css`.
 *
 * The output is a build artifact and is git-ignored: regenerating it must be the
 * only way it changes, so that the token source cannot drift from the CSS that
 * ships. `packages/ui` imports the result.
 */
async function main(): Promise<void> {
  const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
  const outputPath = resolve(packageRoot, 'dist/tokens.css')

  const banner = '/* Generated by @sentra/tokens. Do not edit — edit src/tokens.ts. */\n\n'

  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, banner + buildTokensCss(), 'utf8')

  console.log(`wrote ${outputPath}`)
}

await main()
